# Site settings
title_left    : ""
title_right   : "Hakan Yücel" # default: ""
description   : "Yazılım teknikleri ve teknolojileri üzerine analiz ve çalışmalarım."
keywords      : "c#, javascript, mongodb, pattern, aop, oop"
host          : "htts://yucel.dev"
url           :  ""
app           :  "https://yucel.dev"
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-136368539-1
twitter_username  : "hknyuc"
github_username: "hknyuc"
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "yucel-dev"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Hakan Yücel"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-redirect-from

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
